src/Entity/Uczen.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UczenRepository")
 */
class Uczen implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Imie;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $Nazwisko;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $Klasa;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ocena", mappedBy="uczen", orphanRemoval=true)
     */
    private $oceny;

    public function __construct()
    {
        $this->oceny = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_STUDENT';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getImie(): ?string
    {
        return $this->Imie;
    }

    public function setImie(string $Imie): self
    {
        $this->Imie = $Imie;

        return $this;
    }

    public function getNazwisko(): ?string
    {
        return $this->Nazwisko;
    }

    public function setNazwisko(string $Nazwisko): self
    {
        $this->Nazwisko = $Nazwisko;

        return $this;
    }

    public function getKlasa(): ?string
    {
        return $this->Klasa;
    }

    public function setKlasa(string $Klasa): self
    {
        $this->Klasa = $Klasa;

        return $this;
    }

    /**
     * @return Collection|Ocena[]
     */
    public function getOceny(): Collection
    {
        return $this->oceny;
    }

    public function addOceny(Ocena $oceny): self
    {
        if (!$this->oceny->contains($oceny)) {
            $this->oceny[] = $oceny;
            $oceny->setUczen($this);
        }

        return $this;
    }

    public function removeOceny(Ocena $oceny): self
    {
        if ($this->oceny->contains($oceny)) {
            $this->oceny->removeElement($oceny);
            // set the owning side to null (unless already changed)
            if ($oceny->getUczen() === $this) {
                $oceny->setUczen(null);
            }
        }

        return $this;
    }
}

src/Controller/MainController.php
<?php
namespace App\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

use App\Entity\Ocena;
use App\Entity\Uczen;

class MainController extends AbstractController {

    /**
    * @Route("/", name="main")
    */
    public function showMainPage(Request $request) {
        // render method is from the twig engine
        return $this->render('main/index.html.twig', [
            'controller_name' => 'MainController',
        ]);
    }

    /**
    * @Route("/ocena-confirmation", name="ocena-confirmation")
    */
    public function showConfirmationAfterAddNewGrade() {
        $this->denyAccessUnlessGranted('ROLE_TEACHER');

        $request = Request::createFromGlobals();

        $stopien = $_POST['ocena'];
        $przedmiot = $_POST['przedmiot'];
        $data = $_POST['data'];
        $uczen = $_POST['uczen'];

        // $uczenArr = explode(" ", $uczen);
        // $uczen = $uczenArr[0];

        $uczenObj = $this->getDoctrine()
        ->getRepository(Uczen::class)
        ->find($uczen);

        $ocena = new Ocena();
        $ocena->setOcena($stopien);
        $ocena->setPrzedmiot($przedmiot);
        $ocena->setData(new \DateTime($data));
        $ocena->setUczen($uczenObj);

        $entityManager = $this->getDoctrine()->getManager();

        $entityManager->persist($ocena);
        $entityManager->flush();

        return $this->render('main/ocena-confirmation.html.twig', [
            'controller_name' => 'MainController',
            'uczen' => $uczenObj,
        ]);
    }

    /**
    * @Route("/add-student", name="add-student")
    */
    public function showStudentForm() {
        $this->denyAccessUnlessGranted('ROLE_TEACHER');

        return $this->render('main/add-student.html.twig', [
            'controller_name' => 'MainController',
        ]);
    }

    /**
    * @Route("/uczen-confirmation", name="uczen-confirmation")
    */
    public function showConfirmationAfterAddNewStudent() {
        $this->denyAccessUnlessGranted('ROLE_TEACHER');

        $request = Request::createFromGlobals();

        $firstname = $_POST['firstname'];
        $lastname = $_POST['lastname'];
        $class = $_POST['class'];

        $uczen = new Uczen();
        $uczen->setImie($firstname);
        $uczen->setNazwisko($lastname);
        $uczen->setKlasa($class);
        $uczen->setEmail($this->generateRandomString(10)."@".$this->generateRandomString(3).".".$this->generateRandomString(2));
        $uczen->setPassword("mockpassword");

        $entityManager = $this->getDoctrine()->getManager();

        $entityManager->persist($uczen);
        $entityManager->flush();

        return $this->render('main/uczen-confirmation.html.twig', [
            'controller_name' => 'MainController',
        ]);
    }



    function generateRandomString($length = 10) {
        $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        $randomString = '';
        for ($i = 0; $i < $length; $i++) {
            $randomString .= $characters[rand(0, $charactersLength - 1)];
        }
        return $randomString;
    }
    
}
?>

templates/main/add-student.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panel nauczyciela{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
{% endblock %}

{% block body %}

<div class="container">
<h1 class="display-4">Dziennik ocen</h1>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/show-grades">Sprawdź oceny</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Panel nauczyciela</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="/add-student">Dodaj ucznia</a>
                <a class="dropdown-item" href="/add-grade">Dodaj ocenę</a>
            </div>
        </li>
        {% if not is_granted('IS_AUTHENTICATED_FULLY') %}
            <li class="nav-item">
                <a class="nav-link" href="/login">Logowanie nauczyciela</a>
            </li>
        {% endif %}
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <li class="nav-item">
                <a class="nav-link" href="/logout">Wyloguj</a>
            </li>
        {% endif %}
    </ul>
    <div class="jumbotron">
        <h3>Dodaj ocenę:</h3>
        <form action="/uczen-confirmation" method="post">

            <label for="firstname">Imie:</label>
            <input type="text" id="firstname" name="firstname" class="form-control" required/>
            <label for="lastname">Nazwisko:</label>
            <input type="text" id="lastname" name="lastname" class="form-control" required/>
            <label for="uczen">Klasa:</label>
            <input type="text" id="class" name="class" class="form-control" required/>

            {#
                If you want to control the URL the user
                is redirected to on success (more details below)
                <input type="hidden" name="_target_path" value="/account" />
            #}

            <br>

            <button type="submit" class="btn btn-primary">Dodaj ucznia</button>
        </form>
    </div>
</div>
{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Strona Główna{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
{% endblock %}

{% block body %}

<div class="container">
<h1 class="display-4">Dziennik ocen</h1>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" href="#">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/show-grades">Sprawdź oceny</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Panel nauczyciela</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="/add-student">Dodaj ucznia</a>
                <a class="dropdown-item" href="/add-grade">Dodaj ocenę</a>
            </div>
        </li>
        {% if not is_granted('IS_AUTHENTICATED_FULLY') %}
            <li class="nav-item">
                <a class="nav-link" href="/login">Logowanie nauczyciela</a>
            </li>
        {% endif %}
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <li class="nav-item">
                <a class="nav-link" href="/logout">Wyloguj</a>
            </li>
        {% endif %}
    </ul>
    <div class="jumbotron">
        Strona Główna
        <br>
        <br>
        Wybierz akcję z menu na górze
    </div>
{% endblock %}

templates/main/ocena-confirmation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panel nauczyciela{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
{% endblock %}

{% block body %}

<div class="container">
<h1 class="display-4">Dziennik ocen</h1>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/show-grades">Sprawdź oceny</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/login">Logowanie nauczyciela</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Panel nauczyciela</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="/add-student">Dodaj ucznia</a>
                <a class="dropdown-item" href="/add-grade">Dodaj ocenę</a>
            </div>
        </li>
        {% if not is_granted('IS_AUTHENTICATED_FULLY') %}
            <li class="nav-item">
                <a class="nav-link" href="/login">Logowanie nauczyciela</a>
            </li>
        {% endif %}
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <li class="nav-item">
                <a class="nav-link" href="/logout">Wyloguj</a>
            </li>
        {% endif %}
    </ul>
    <div class="jumbotron">
        Dodano ocenę.
        <br>
        <br>
        <br>
        <a href="/add-grade">Powrót</a>
    </div>
</div>
{% endblock %}

templates/main/show-grades.html.twig
{% extends 'base.html.twig' %}

{% block title %}Oceny{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
{% endblock %}

{% block body %}

<div class="container">
<h1 class="display-4">Dziennik ocen</h1>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="#">Sprawdź oceny</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Panel nauczyciela</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="/add-student">Dodaj ucznia</a>
                <a class="dropdown-item" href="/add-grade">Dodaj ocenę</a>
            </div>
        </li>
        {% if not is_granted('IS_AUTHENTICATED_FULLY') %}
            <li class="nav-item">
                <a class="nav-link" href="/login">Logowanie nauczyciela</a>
            </li>
        {% endif %}
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <li class="nav-item">
                <a class="nav-link" href="/logout">Wyloguj</a>
            </li>
        {% endif %}
        
    </ul>
    <div class="jumbotron">
        <table class="table table-striped">
            <thead>
                <tr>
                <th scope="col">Przedmiot</th>
                <th scope="col">Ocena</th>
                <th scope="col">Data</th>
                <th scope="col">Uczeń</th>
                <th scope="col">Klasa</th>
                {# {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <th scope="col">Akcja</th>
                {% endif %} #}
                
                </tr>
            </thead>
            <tbody>
                {% for ocena in oceny %}
                <trscope="row">
                    <td>{{ocena.przedmiot}}</td>
                    <td>{{ocena.ocena}}</td>
                    <td>{{ocena.data.format("Y-m-d")}}</td>
                    <td>{{ocena.uczen.imie}} {{ocena.uczen.nazwisko}}</td>
                    <td>{{ocena.uczen.klasa}}</td>
                    {# {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <td>
                        <form action="/edit-grade/{{ocena.id}}">
                            <button type="submit" class="btn btn-primary">Edytuj</button>
                        </form>
                    </td>
                    {% endif %} #}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
        <br>
    </div>
{% endblock %}

templates/main/uczen-confirmation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panel nauczyciela{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
{% endblock %}

{% block body %}

<div class="container">
<h1 class="display-4">Dziennik ocen</h1>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/show-grades">Sprawdź oceny</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/login">Logowanie nauczyciela</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Panel nauczyciela</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="/add-student">Dodaj ucznia</a>
                <a class="dropdown-item" href="/add-grade">Dodaj ocenę</a>
            </div>
        </li>
        {% if not is_granted('IS_AUTHENTICATED_FULLY') %}
            <li class="nav-item">
                <a class="nav-link" href="/login">Logowanie nauczyciela</a>
            </li>
        {% endif %}
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <li class="nav-item">
                <a class="nav-link" href="/logout">Wyloguj</a>
            </li>
        {% endif %}
    </ul>
    <div class="jumbotron">
        Dodano ucznia.
        <br>
        <br>
        <br>
        <a href="/add-student">Powrót</a>
    </div>
</div>
{% endblock %}